export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userConstants = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};

export const categoryConstants = {
  GET_ALL_REQUEST: "GET_ALL_REQUEST",
  GET_ALL_FAILURE: "GET_ALL_FAILURE",
  GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
  ADD_REQUEST: "ADD_REQUEST",
  ADD_FAILURE: "ADD_FAILURE",
  ADD_SUCCESS: "ADD_SUCCESS",
};
