export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
};
export const productConstants = {
  GET_PRODUCT_BY_SLUG: "GET_PRODUCT_BY_SLUG",
  GET_PAGE_REQUEST: "GET_PAGE_REQUEST",
  GET_PAGE_FAILURE: "GET_PAGE_FAILURE",
  GET_PAGE_SUCCESS: "GET_PAGE_SUCCESS",
};
